### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vvp3** [schroef/Save-Custom-Weight-Paint-Presets#1]
**OS:**
 - OS: [e.g. OSX, Windows, Linux]
 - windows

**ADDON:**
 - Version: [e.g.: Release date or Version]
 - 0.0.6

**Describe the bug**

in blender 3.1.2
when enabling i have the following error:

Traceback (most recent call last):
  File "C:\_____testing BLENDER\___blender_3_2022\stable\blender-3.1.2-windows-x64\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\VP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Save-Custom-Weight-Paint-Presets\__init__.py", line 227, in register
    install_presets()
  File "C:\Users\VP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Save-Custom-Weight-Paint-Presets\__init__.py", line 120, in install_presets
    destination = bpy.utils.user_resource('SCRIPTS',
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**To Reproduce**

**Screenshots**

**Comment by schroef** [comment]
Thanks for posting this, i have not found time yet to even install and test 3.0

My plan is to add new code i have been working on. With you can also load and save gradient presets with the node color ramp.

I'm hoping to combine them asap

**Comment by schroef** [comment]
@vvp3 
i believe the new release [0.0.8](https://github.com/schroef/Save-Custom-Weight-Paint-Presets/releases/tag/v0.0.8) should fix the error showing when trying to install the addon
